# Generated by Django 4.2.7 on 2026-03-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_learning', '0009_question_correct_answer_question_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='test_generation_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studysession',
            name='test_generation_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
